### ISSUE TITLE
Add comments to properties in meta model

### ISSUE THREAD

**Issue by KonradHoeffner** [IMISE/snik-ontology#198]
Add rdfs:comment to all properties of the meta model

**Comment by KonradHoeffner** [comment]
Don't forget the upcoming isResponsibleForRole relation, see #196.

**Comment by KonradHoeffner** [comment]
There are 34 of those:

- [ ] http://www.snik.eu/ontology/meta/book
- [ ] http://www.snik.eu/ontology/meta/subChapterOf
- [ ] http://www.snik.eu/ontology/meta/accesses
- [ ] http://www.snik.eu/ontology/meta/changes
- [ ] http://www.snik.eu/ontology/meta/component
- [ ] http://www.snik.eu/ontology/meta/chapter
- [ ] http://www.snik.eu/ontology/meta/communicatesWith
- [ ] http://www.snik.eu/ontology/meta/decreases
- [ ] http://www.snik.eu/ontology/meta/increases
- [ ] http://www.snik.eu/ontology/meta/isBasedOn
- [ ] http://www.snik.eu/ontology/meta/isevolved
- [ ] http://www.snik.eu/ontology/meta/supports
- [ ] http://www.snik.eu/ontology/meta/uses
- [ ] http://www.snik.eu/ontology/meta/isAssociatedWith
- [ ] http://www.snik.eu/ontology/meta/updates
- [ ] http://www.snik.eu/ontology/meta/homonym
- [ ] http://www.snik.eu/ontology/meta/approvesEntityType
- [ ] http://www.snik.eu/ontology/meta/approvesFunction
- [ ] http://www.snik.eu/ontology/meta/isResponsibleForEntityType
- [ ] http://www.snik.eu/ontology/meta/isResponsibleForFunction
- [ ] http://www.snik.eu/ontology/meta/represents
- [ ] http://www.snik.eu/ontology/meta/softwareProduct
- [ ] http://www.snik.eu/ontology/meta/entityTypeComponent
- [ ] http://www.snik.eu/ontology/meta/functionComponent
- [ ] http://www.snik.eu/ontology/meta/roleComponent
- [ ] http://www.snik.eu/ontology/meta/approves
- [ ] http://www.snik.eu/ontology/meta/subTopClass
- [ ] http://www.snik.eu/ontology/meta/isResponsibleFor
- [ ] http://www.snik.eu/ontology/meta/chapterNumber
- [ ] http://www.snik.eu/ontology/meta/firstPage
- [ ] http://www.snik.eu/ontology/meta/lastPage
- [ ] http://www.snik.eu/ontology/meta/defined
- [ ] http://www.snik.eu/ontology/meta/evaluated
- [ ] http://www.snik.eu/ontology/meta/referenced

**Comment by KonradHoeffner** [comment]
`rdfs:comment` would actually be fine as well but it needs to be consistent.

**Comment by KonradHoeffner** [comment]
I added the comments but it would be good if @FranziskaJahn can check them.
